

spring:
  application:
    name: emtech_ems

  datasource:
    url: jdbc:postgresql://localhost:5432/emtech_ems
    username: postgres
    password: Passcrypt@101
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        boot:
          allow_jdbc_metadata_access: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

